PROGRAM EXAMPLE
  ! THIS IS AN EXAMPLE PROGRAM TO DEMONSTRATE SOME
  ! FEATURES OF THE SOURCE CODE CONVERSION FROM
  ! FORTRAN FIXED FORMAT TO FORTRAN FREE FORMAT
  ! BY THE FFIXED2FREE PROGRAM
  IMPLICIT NONE

  ! DECLARATION: FFIXED2FREE ADDS DOUBLE-COLON
  INTEGER :: IX, JY
  ! BUT DOES NOT MODIFY THE LINE IF A COLON IS ALREAY PRESENT
  REAL ::      Z
  ! CHARACTER: FFIXED2FREE REPLACES STAR AND NUMBER BY len=
  CHARACTER(len=255) :: LINE

  ! INITIALIZATION
  JY = 1

  ! DO LOOP WITH ENDDO
  ! INLINE COMMENT:
  ! FFIXED2FREE INDENTS INLINE COMMENT
  PRINT *,'LOOP1'
  DO IX=0,5
  ! THIS IS NOT AN INLINE COMMENT
     ! THIS IS AN INLINE COMMENT
     ! PRINT VALUE OF IX
     PRINT *,'IX=',IX
  END DO

  ! DO LOOP WITH LABEL AND CONTINUE
  ! FFIXED2FREE REPLACES LABEL AND CONTINUE BY END DO
  PRINT *,'LOOP2'
  DO IX=0,5
     ! PRINT VALUE OF IX
     PRINT *,'IX=',IX
  END DO

  ! DO LOOP WITH LABEL AND CONTINUE
  ! FFIXED2FREE DOES NOT REPLACE LABEL AND CONTINUE IF LABEL IS
  ! NOT SOLELY END LABEL OF DO LOOP
  PRINT *,'LOOP2'
  DO IX=0,5
     ! GOTO TO DEMONSTRATE EFFECT OF SECOND USE OF LABEL
     IF (IX .GT. 10) GOTO 2
     ! PRINT VALUE OF IX
     PRINT *,'IX=',IX
 2  CONTINUE
  END DO

  ! NESTED IF STATEMENTS WITH INLINE COMMENTS
  ! FFIXED2FREE MOVES START OF COMMENT TO MATCH INDENT
  IF (IX .GT. 5) THEN
     ! PRINT MESSAGE WHEN FIRST CONDITION IS MET
     PRINT *,'IX > 5'
     IF (JY .GT. 0) THEN
        ! PRINT MESSAGE WHEN BOTH CONDITIONS ARE MET
        PRINT *,'IX > 5 AND JY > 0'
     END IF
  END IF

  ! LONG IF STATEMENT WITH CONTINUATION
  ! FFIXED2FREE ADDS AMPERSAND ON PRECEDING LINE
  IF (IX .GT. 5 &
        .AND. JY .GT. 0) &
        THEN
     ! PRINT MESSAGE
     PRINT *,'IX > 5 AND JY > 0'
  ENDIF

  ! LONG CHARACTER STRING (PAST COLUMN 72) WITH CONTINUATION ON NEXT LINE
  ! FFIXED2FREE DOES NOT TRUNCATE LINES LONGER THAN 72 CHARS
  LINE = 'THIS IS A REALLY VERY LONG TEXT, WITHOUT MUCH MEANING, BUT WHITH A&
        & CONTINUATION ON THE NEXT LINE'
  PRINT *,LINE

  ! END STATEMENT: FFIXED2FREE ADDS PROGRAM NAME
END PROGRAM EXAMPLE
