      PROGRAM EXAMPLE
C THIS IS AN EXAMPLE PROGRAM TO DEMONSTRATE SOME
C FEATURES OF THE SOURCE CODE CONVERSION FROM
C FORTRAN FIXED FORMAT TO FORTRAN FREE FORMAT
C BY THE FFIXED2FREE PROGRAM
      IMPLICIT NONE

C DECLARATION: FFIXED2FREE ADDS DOUBLE-COLON
      INTEGER IX, JY
C BUT DOES NOT MODIFY THE LINE IF A COLON IS ALREAY PRESENT
      REAL ::      Z
C CHARACTER: FFIXED2FREE REPLACES STAR AND NUMBER BY len=
      CHARACTER*255 LINE

C INITIALIZATION
      JY = 1

C DO LOOP WITH ENDDO
C INLINE COMMENT:
C FFIXED2FREE INDENTS INLINE COMMENT
      PRINT *,'LOOP1: COUNT IX TO 5'
      DO IX=0,5
C THIS IS NOT AN INLINE COMMENT
C        THIS IS AN INLINE COMMENT
C        PRINT VALUE OF IX
         PRINT *,'IX=',IX
      END DO
      PRINT *, 'AFTER LOOP1 IX=', IX


C DO LOOP WITH LABEL AND CONTINUE
C FFIXED2FREE REPLACES LABEL AND CONTINUE BY END DO
      PRINT *,'LOOP2: COUNT IX TO 5'
      DO 1 IX=0,5
C        PRINT VALUE OF IX
         PRINT *,'IX=',IX
 1    CONTINUE
      PRINT *, 'AFTER LOOP2 IX=', IX

C DO LOOP WITH LABELED CONTINUE AND A GOTO POINTING TO IT
C FFIXED2FREE DOES NOT REPLACE LABEL AND CONTINUE IF LABEL IS
C NOT SOLELY END LABEL OF DO LOOP
      PRINT *,'LOOP3: COUNT IX TO 5 BUT STOP PRINTING AT 3'
      DO 2 IX=0,5
C        GOTO TO DEMONSTRATE EFFECT OF SECOND USE OF LABEL
         IF (IX .GT. 2) GOTO 2
C        PRINT VALUE OF IX
         PRINT *,'IX=',IX
 2    CONTINUE
      PRINT *, 'AFTER LOOP3 IX=', IX

C DO LOOP WITH LABELED STATEMENT WITH A GOTO POINTING TO IT
      PRINT *,'LOOP4: COUNT IX TO 5 AND SET JY TO IX IF IT IS > 2'
      JY = 0
      DO 3 IX=0,5
      IF (IX .GT. 2) GOTO 3
      PRINT *, 'IN LOOP IX=', IX
      PRINT *, 'IN LOOP JY=', JY
    3 JY = IX
      PRINT *, 'AFTER LOOP4 IX=', IX, 'JY=', JY

C NESTED IF STATEMENTS WITH INLINE COMMENTS
C FFIXED2FREE MOVES START OF COMMENT TO MATCH INDENT
      IF (IX .GT. 5) THEN
C        PRINT MESSAGE WHEN FIRST CONDITION IS MET
         PRINT *,'IX > 5'
         IF (JY .GT. 0) THEN
C           PRINT MESSAGE WHEN BOTH CONDITIONS ARE MET
            PRINT *,'IX > 5 AND JY > 0'
         END IF
      END IF

C LONG IF STATEMENT WITH CONTINUATION
C FFIXED2FREE ADDS AMPERSAND ON PRECEDING LINE
      IF (IX .GT. 5 
     .     .AND. JY .GT. 0)
     .     THEN
C        PRINT MESSAGE
         PRINT *,'IX > 5 AND JY > 0'
      ENDIF

C LONG CHARACTER STRING (PAST COLUMN 72) WITH CONTINUATION ON NEXT LINE
C FFIXED2FREE DOES NOT TRUNCATE LINES LONGER THAN 72 CHARS
      LINE = 'THIS IS A REALLY VERY LONG TEXT, WITHOUT MUCH MEANING, BUT WHITH A
     . CONTINUATION ON THE NEXT LINE'
      PRINT *,LINE

C END STATEMENT: FFIXED2FREE ADDS PROGRAM NAME
      END
