void setBuildStatus(String message, String state) {
  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/my-org/my-repo"],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/build-status"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}

pipeline {
    agent {
        label 'tsa'
    }
    post {
        always{
            echo 'Cleaning up workspace'
            deleteDir()
        }
        success {
            setBuildStatus("Build succeeded", "SUCCESS");
        }
        failure {
            setBuildStatus("Build failed", "FAILURE");
        }
    }
    stages {
        stage('Build') { 
            steps {
	    	sh '''#!/bin/bash
     	    	cd src
	    	make
                ''' 
            }
        }
        stage('Test') { 
            steps {
                sh '''
		./src/ffixed2free
		'''
            }
        }
    }
}
